"""update models

Revision ID: 9b5dadb9271c
Revises: dc0e61d7343a
Create Date: 2025-10-24 09:39:36.209795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b5dadb9271c'
down_revision: Union[str, None] = 'dc0e61d7343a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('site_project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assets', 'site_projects', ['site_project_id'], ['id'], ondelete='SET NULL')
    op.add_column('slot_bookings', sa.Column('site_project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'slot_bookings', 'site_projects', ['site_project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'slot_bookings', type_='foreignkey')
    op.drop_column('slot_bookings', 'site_project_id')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_column('assets', 'site_project_id')
    # ### end Alembic commands ###
