"""add user password column and email_verified flag

Revision ID: 9f973e2f9225
Revises: d31e127f7859
Create Date: 2025-10-24 13:34:15.849856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f973e2f9225'
down_revision: Union[str, None] = 'd31e127f7859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('MANAGER', 'ADMIN', name='userrole'),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('MANAGER', 'ADMIN', name='userrole'),
               existing_nullable=False)
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
