"""make_notifications_activity_id_nullable

Revision ID: a1b2c3d4e5f6
Revises: f9a0b1c2d3e4
Create Date: 2026-03-24

Makes notifications.activity_id nullable and changes its ON DELETE behaviour
from CASCADE to SET NULL.

Reason: notifications are lookahead-driven demand-gap alerts, not per-activity
assignments. Requiring a non-null activity_id blocks the creation of any
notification that is not tied to a specific programme activity (e.g. weekly
asset-demand gap alerts generated by the lookahead engine).

With SET NULL, deleting a programme activity orphans the notification row
rather than silently cascading the delete — preserving the alert history.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, None] = "f9a0b1c2d3e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Drop the existing FK constraint (CASCADE delete).
    #    The constraint name follows SQLAlchemy's default naming convention:
    #    notifications_activity_id_fkey
    op.drop_constraint(
        "notifications_activity_id_fkey",
        "notifications",
        type_="foreignkey",
    )

    # 2. Make the column nullable.
    op.alter_column(
        "notifications",
        "activity_id",
        existing_type=sa.UUID(),
        nullable=True,
    )

    # 3. Re-add the FK with SET NULL so deleting an activity does not
    #    silently remove the notification history.
    op.create_foreign_key(
        "notifications_activity_id_fkey",
        "notifications",
        "programme_activities",
        ["activity_id"],
        ["id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    # Remove any rows where activity_id is NULL before restoring NOT NULL —
    # otherwise the downgrade will fail on existing data.
    op.execute(
        "DELETE FROM notifications WHERE activity_id IS NULL"
    )

    op.drop_constraint(
        "notifications_activity_id_fkey",
        "notifications",
        type_="foreignkey",
    )

    op.alter_column(
        "notifications",
        "activity_id",
        existing_type=sa.UUID(),
        nullable=False,
    )

    op.create_foreign_key(
        "notifications_activity_id_fkey",
        "notifications",
        "programme_activities",
        ["activity_id"],
        ["id"],
        ondelete="CASCADE",
    )
