"""removed sub user relation

Revision ID: ac2d91bc1a20
Revises: ec1ed26152c5
Create Date: 2025-10-24 23:03:21.816903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac2d91bc1a20'
down_revision: Union[str, None] = 'ec1ed26152c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
