"""create_initial_tables_with_all_models

Revision ID: dc0e61d7343a
Revises: ee60530b06cc
Create Date: 2025-10-24 08:31:02.994061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc0e61d7343a'
down_revision: Union[str, None] = 'ee60530b06cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('img_path', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_uploads_id'), 'file_uploads', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('manager', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('site_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_key', sa.String(), nullable=True),
    sa.Column('email_id', sa.String(), nullable=True),
    sa.Column('contractor_project', sa.Text(), nullable=True),
    sa.Column('contractor_project_id', sa.String(), nullable=True),
    sa.Column('contractor_name', sa.String(), nullable=True),
    sa.Column('contractor_company', sa.String(), nullable=True),
    sa.Column('contractor_trade', sa.String(), nullable=True),
    sa.Column('contractor_email', sa.String(), nullable=True),
    sa.Column('contractor_phone', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_projects_contractor_key'), 'site_projects', ['contractor_key'], unique=True)
    op.create_index(op.f('ix_site_projects_id'), 'site_projects', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('user_phone', sa.String(), nullable=True),
    sa.Column('profile_pic', sa.String(), nullable=True),
    sa.Column('credit_point', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('dob', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('asset_title', sa.String(), nullable=False),
    sa.Column('asset_location', sa.String(), nullable=True),
    sa.Column('asset_status', sa.String(), nullable=True),
    sa.Column('asset_poc', sa.String(), nullable=True),
    sa.Column('maintenance_start_dt', sa.String(), nullable=True),
    sa.Column('maintenance_end_dt', sa.String(), nullable=True),
    sa.Column('usage_instructions', sa.Text(), nullable=True),
    sa.Column('asset_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_key'), 'assets', ['asset_key'], unique=True)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_table('slot_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('booking_title', sa.String(), nullable=False),
    sa.Column('booking_for', sa.String(), nullable=True),
    sa.Column('booked_assets', sa.Text(), nullable=True),
    sa.Column('booking_status', sa.String(), nullable=True),
    sa.Column('booking_time_dt', sa.String(), nullable=True),
    sa.Column('booking_duration_mins', sa.Integer(), nullable=True),
    sa.Column('booking_description', sa.Text(), nullable=True),
    sa.Column('booking_notes', sa.Text(), nullable=True),
    sa.Column('booking_created_by', sa.String(), nullable=True),
    sa.Column('booking_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slot_bookings_booking_key'), 'slot_bookings', ['booking_key'], unique=True)
    op.create_index(op.f('ix_slot_bookings_id'), 'slot_bookings', ['id'], unique=False)
    op.create_table('subcontractors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email_id', sa.String(), nullable=True),
    sa.Column('contractor_name', sa.String(), nullable=True),
    sa.Column('contractor_company', sa.String(), nullable=True),
    sa.Column('contractor_trade', sa.String(), nullable=True),
    sa.Column('contractor_email', sa.String(), nullable=True),
    sa.Column('contractor_phone', sa.String(), nullable=True),
    sa.Column('contractor_pass', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcontractors_id'), 'subcontractors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subcontractors_id'), table_name='subcontractors')
    op.drop_table('subcontractors')
    op.drop_index(op.f('ix_slot_bookings_id'), table_name='slot_bookings')
    op.drop_index(op.f('ix_slot_bookings_booking_key'), table_name='slot_bookings')
    op.drop_table('slot_bookings')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_key'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_site_projects_id'), table_name='site_projects')
    op.drop_index(op.f('ix_site_projects_contractor_key'), table_name='site_projects')
    op.drop_table('site_projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_file_uploads_id'), table_name='file_uploads')
    op.drop_table('file_uploads')
    # ### end Alembic commands ###
