"""changes to proejct and contractor

Revision ID: ec1ed26152c5
Revises: c274b24c5e9a
Create Date: 2025-10-24 22:55:51.061318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec1ed26152c5'
down_revision: Union[str, None] = 'c274b24c5e9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_projects', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('site_projects', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('site_projects', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('site_projects', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('site_projects', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('site_projects', sa.Column('status', sa.String(length=50), nullable=True))
    op.drop_index('ix_site_projects_contractor_key', table_name='site_projects')
    op.drop_index('ix_site_projects_contractor_project_id', table_name='site_projects')
    op.drop_column('site_projects', 'email_id')
    op.drop_column('site_projects', 'contractor_project')
    op.drop_column('site_projects', 'contractor_project_id')
    op.drop_column('site_projects', 'contractor_key')
    op.drop_column('site_projects', 'created_by')
    op.add_column('subcontractor_site_project', sa.Column('subcontractor_id', sa.UUID(), nullable=True))
    op.drop_constraint('subcontractor_site_project_user_id_fkey', 'subcontractor_site_project', type_='foreignkey')
    op.create_foreign_key(None, 'subcontractor_site_project', 'subcontractors', ['subcontractor_id'], ['id'])
    op.drop_column('subcontractor_site_project', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcontractor_site_project', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subcontractor_site_project', type_='foreignkey')
    op.create_foreign_key('subcontractor_site_project_user_id_fkey', 'subcontractor_site_project', 'users', ['user_id'], ['id'])
    op.drop_column('subcontractor_site_project', 'subcontractor_id')
    op.add_column('site_projects', sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('site_projects', sa.Column('contractor_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('site_projects', sa.Column('contractor_project_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('site_projects', sa.Column('contractor_project', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('site_projects', sa.Column('email_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_site_projects_contractor_project_id', 'site_projects', ['contractor_project_id'], unique=False)
    op.create_index('ix_site_projects_contractor_key', 'site_projects', ['contractor_key'], unique=False)
    op.drop_column('site_projects', 'status')
    op.drop_column('site_projects', 'end_date')
    op.drop_column('site_projects', 'start_date')
    op.drop_column('site_projects', 'location')
    op.drop_column('site_projects', 'description')
    op.drop_column('site_projects', 'name')
    # ### end Alembic commands ###
